title: Jyo Aala
logo: /assets/img/logo.png
description: Supply Chain professional pursuing an MS in Supply Chain Analytics at Cal State University San Marcos.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
